name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deply:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Rename txt files
        run: |
          find . -type f -name '*.txt' -exec sh -c 'x="{}"; mv "$x" "${x/\.txt$/\.md}"' \;

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
