name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deply:
    name: Deploys stuff to gh-pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Rename txt files
        run: |
          find . -type f -name '*.txt' -exec sh -c 'x="{}"; mv "$x" "$(echo "$x" |rev |cut -c 4- |rev)md"' \;

      - name: Create PDF files
        uses: pistatium/markdown-pdf:9.0.0
        run: |
          find . -type f -name '*.md' -exec sh -c 'x="{}"; markdown-pdf -o "$(echo "$x" |rev |cut -c 3- |rev)pdf" "$x"' \;

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
          CLEAN: true
